/***************************************************************

							NOISE EFFECT COMPILER

			Based on D3DCompile and other "Reflection" sort of 
			D3D api , compiler an .fx file into Noise Effect Binary
			(but some syntax might be extended).
			Noise Effect framework is designed to organized shaders
			in some forms, and this compiler is used to generate
			sufficient information for Noise Effect Framework

***********************************************************/

#pragma once
#pragma warning (disable : 4005)//macro redefined WIN8 SDKºÍDXSDK

#define ERROR_MSG(msg)\
std::cout<<msg<<std::endl;\

#include <iostream>
#include <string>
#include <vector>
#include <fstream>
#include <algorithm>
#include <unordered_set>
#include <unordered_map>
#include <d3d11shader.h>
#include <D3DCompiler.h>

#include "IFactory.h" 
#include "EffectTypeDecl.h"
#include "_ShaderInclude.h"
#include "EffectTokenizer.h"
#include "EffectParser.h"
#include "ShaderReflector.h"
#include "FileWriter.h"

namespace NoiseEffectCompiler
{

	class IEffectCompiler
	{
	public:

		IEffectCompiler();

		bool		ParseCommandLine(int argc, char* argv[]);

		bool		Compile();

		IEffect* GetEffectInterface();

	private:

		bool		mFunction_LoadParameters(int argc, char* argv[]);

		bool		mFunction_LoadFiles();

		bool		mFunction_ParseEffect(std::vector<N_SHADER_DESC>& outShaderList,std::vector<std::string>& outSourceFileList);

		bool		mFunction_CompileHLSL(std::vector<N_SHADER_DESC>& in_uniqueShaderList, std::vector<N_UNIQUE_SHADER>& out_uniqueShaderList, const std::vector<std::string>& sourceFileList);

		bool		mFunction_ShaderReflection( std::vector<N_UNIQUE_SHADER>& in_out_uniqueShaderList);

		bool		mFunction_CompleteShaderDescOfEffectHierarchy();

		bool		mFunction_OutputCompiledEffectFile();

		//obtained by loading cmd parameters and effect file
		std::string mTargetFileName;
		std::string mEffectFileName;
		std::vector<unsigned char> mEffectFileBuffer;
		std::string mRelativePath;


		IEffect					mEffect;
		IEffectTokenizer	mTokenizer;
		IEffectParser		mParser;
		IShaderReflector	mShaderReflector;
		IFileWriter			mFileWriter;

		//information generated by ShaderReflector
		std::unordered_map<std::string, N_UNIQUE_SHADER> mUniqueShaderTable;
	};

}

